version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          # You can get this ID in the section where you registered the SSH Key
          fingerprints: [
              "d1:f0:10:05:aa:91:4b:7f:b1:fa:2f:56:44:33:2d:07
              ",
            ]
      - run:
          name: Install Ansible
          command: |
            # Install Ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            apk add --update ansible
      - run:
        name: Configure server
        command: |
          ansible-playbook -i inventory.txt main.yml

# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      # - create_infrastructure
      - configure_infrastructure
